name: Metrics
on:
  # 每天 0 点更新一次
  schedule: [{cron: "0 0 * * *"}]
  # 允许手动触发
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # 这个文件会生成在你的仓库根目录，名字叫 github-metrics.svg
          filename: github-metrics.svg
          
          # 基础配置
          user: blueberrycongee
          template: classic
          base: "" # 关闭基础信息，只显示我们想要的插件
          config_timezone: Asia/Shanghai
          
          # 【核心】开启代码行数统计插件
          plugin_lines: yes
          plugin_lines_history_limit: 1  # 统计历史年限（1年）
          plugin_lines_repositories_limit: 4 # 统计最活跃的4个仓库（太多会超时）
          plugin_lines_sections: base # 展示新增/删除的基础图表
